version: '3'

services:
  youtube-video-stats:
    build:
      context: services/app
      dockerfile: Dockerfile
    volumes:
        - .:/usr/src/app
    ports:
      - 5000:5000
    env_file:
      - ./services/app/.env